/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    val f1 = Fraccion(1, 4)
    f1.mostrar()
    val f2 = Fraccion(3, 4)
    f2.mostrar()
    var f3 = f1 + f2
    var f4 = f1 - f2
    var f5 = f1 * f2
    var f6 = f1 / f2
    var decimal = 0.5
    val fdecimal = Fraccion.desdeDecimal(decimal)
    println("Suma: $f1 + $f2 = ${f3}")
    println("Resta: $f1 - $f2 = ${f4}")
    println("Multiplicacion: $f1 * $f2 = ${f5}")
    println(f1.compareTo(f2))
    println(f1 == f2)
    println(f1 > f2)
    println(f1 < f2)
    println(f1.aDecimal())
    println("Decimal $decimal como fracción: $fdecimal")
}
