/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    val f1 = Fraccion(3, 4)
    f1.mostrar()
    val f2 = Fraccion(1, 4)
    f2.mostrar()
    var f3 = f1 + f2
    var f4 = f1 - f2
    println("Suma: $f1 + $f2 = ${f3}")
    println("Resta: $f1 - $f2 = ${f4}")
}
